//! #186 — the ONE trustworthy, binary zero-loss check.
//!
//! Replaces the muddled per-hop loss metrics (`dropped` / `phantom` / `gap` /
//! painter-tick beat / `real_gap`) with a SINGLE definitive check that a
//! non-engineer can trust:
//!
//!   Each rendered frame carries a DIGITAL monotonic burn id — a per-node counter
//!   generated in our own code (cam1-capture burn, strih burn, stream burn). Every
//!   node forwards its burn into the stream program output, so the SINGLE stream
//!   recording carries all three burn-id sequences.
//!
//!   THE CHECK: is each node's burn-id sequence, as decoded from the STREAM
//!   recording, CONTIGUOUS — every consecutive integer from first..=last present,
//!   no gap?
//!
//!   - Contiguous ⇒ ZERO loss for that hop: every frame the node rendered reached
//!     the recording.
//!   - A missing id ⇒ ONE candidate dropped frame, classified definitively by
//!     viewing the pixels at that position in the recording:
//!       * the frame is PRESENT but its burn QR is unreadable (the frame and its
//!         OTHER QRs decode) ⇒ a BURN-READABILITY defect to FIX, NOT a frame drop
//!         (the burn is digitally generated by our own code, so it MUST be made
//!         readable — bigger / crisper). Reported, never silently excluded.
//!       * the frame is genuinely ABSENT (no frame at that grid slot, black /
//!         garbage) ⇒ a REAL dropped frame.
//!
//! No percentages, no jargon. The output is the single binary:
//!   "ZERO loss: all burn-id sequences contiguous (N frames, M seconds)"
//!   OR "NOT zero: <list> — each id: REAL DROP (pixel) or BURN-UNREADABLE (pixel)".
//!
//! This module holds the PURE contiguity check (`burn_contiguity`,
//! [`NodeContiguity`]) — fully unit-tested with synthetic burn-id sequences. The
//! pixel classification of each missing id is the I/O glue in the
//! `recording-verdict` binary (it re-decodes neighboring recorded frames), kept out
//! of this pure module so the trustworthy logic is independently provable.

use serde::Serialize;

/// The contiguity verdict for ONE node's burn-id sequence (decoded from the stream
/// recording). Contiguous (`missing_ids` empty) ⇒ ZERO loss for that node's
/// delivery into the recording.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NodeContiguity {
    /// Node label, e.g. `"cam1"`, `"strih"`, `"stream"`.
    pub node: String,
    /// First burn id seen (the start of the analyzed span). `None` ⇒ no burn at all.
    pub first_id: Option<u32>,
    /// Last burn id seen (the end of the analyzed span). `None` ⇒ no burn at all.
    pub last_id: Option<u32>,
    /// How many DISTINCT burn ids were decoded.
    pub present_count: u32,
    /// How many ids the contiguous span `first..=last` should contain.
    pub expected_count: u32,
    /// The exact ids missing from `first..=last`, sorted ascending. Empty ⇒ contiguous.
    /// Each entry is ONE candidate dropped frame to be classified by pixel.
    pub missing_ids: Vec<u32>,
}

impl NodeContiguity {
    /// ZERO loss for this node ⇔ the burn-id sequence is contiguous (no missing id).
    /// A node that rendered NO burn (`first_id == None`) is NOT a pass — there is
    /// nothing to prove zero on, which must never read as success.
    pub fn is_contiguous(&self) -> bool {
        self.first_id.is_some() && self.missing_ids.is_empty()
    }
}

/// THE trustworthy check, pure: given the burn ids one node rendered that reached
/// the stream recording (the [`crate::probe::recording_latency::burn_ids_in`]
/// output for that node's run_id), report whether the sequence is contiguous and,
/// if not, EVERY missing id.
///
/// Duplicates are collapsed (the 60→30 sampling beat puts one render id on several
/// recorded frames — the SAME integer, never loss). Order is irrelevant (a set
/// membership test over `first..=last`). The span is `min(ids)..=max(ids)`; an id
/// missing inside that span is a candidate dropped frame.
///
/// An empty input ⇒ `first_id == None` ⇒ NOT contiguous (nothing proven). A
/// single-id input is trivially contiguous (span of one, nothing can be missing).
pub fn burn_contiguity(node: &str, ids: &[u32]) -> NodeContiguity {
    use std::collections::BTreeSet;
    let present: BTreeSet<u32> = ids.iter().copied().collect();
    let first_id = present.iter().next().copied();
    let last_id = present.iter().next_back().copied();
    let (first, last) = match (first_id, last_id) {
        (Some(f), Some(l)) => (f, l),
        _ => {
            return NodeContiguity {
                node: node.to_string(),
                first_id: None,
                last_id: None,
                present_count: 0,
                expected_count: 0,
                missing_ids: Vec::new(),
            };
        }
    };
    // expected = last - first + 1 (the size of the contiguous integer span). Saturating math
    // so a degenerate full-u32-range span (unreachable for run-bounded CRC-validated burn ids,
    // but defensive) can never panic on a debug-build overflow.
    let expected_count = (last - first).saturating_add(1);
    let present_count = present.len() as u32;
    let missing_ids: Vec<u32> = (first..=last).filter(|id| !present.contains(id)).collect();
    NodeContiguity {
        node: node.to_string(),
        first_id: Some(first),
        last_id: Some(last),
        present_count,
        expected_count,
        missing_ids,
    }
}

/// One IN-WINDOW recorded delivered frame's burn status for a node (#198).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RecordedBurnFrame {
    /// 0-based recorded frame_index (for slot location / pixel proof).
    pub frame_index: u64,
    /// This node's burn id decoded on the frame, or `None` if the burn was not readable.
    pub burn_id: Option<u32>,
}

/// THE in-window contiguity check (#198). RED STUB: still delegates to the buggy
/// integer-range `burn_contiguity` over the present ids, so it over-counts the
/// per-render-tick forward skips as "missing". The GREEN fix replaces this body.
pub fn burn_contiguity_in_window(node: &str, frames: &[RecordedBurnFrame]) -> NodeContiguity {
    let ids: Vec<u32> = frames.iter().filter_map(|f| f.burn_id).collect();
    burn_contiguity(node, &ids)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn contiguous_sequence_is_zero_loss() {
        let ids = [100, 101, 102, 103, 104];
        let c = burn_contiguity("stream", &ids);
        assert!(c.is_contiguous(), "no gap ⇒ zero loss: {c:?}");
        assert!(c.missing_ids.is_empty());
        assert_eq!(c.first_id, Some(100));
        assert_eq!(c.last_id, Some(104));
        assert_eq!(c.present_count, 5);
        assert_eq!(c.expected_count, 5);
    }

    #[test]
    fn one_missing_id_is_one_candidate_drop() {
        // 102 is missing inside [100,104] — exactly ONE candidate dropped frame.
        let ids = [100, 101, 103, 104];
        let c = burn_contiguity("strih", &ids);
        assert!(!c.is_contiguous(), "a gap is NOT zero loss");
        assert_eq!(c.missing_ids, vec![102]);
        assert_eq!(c.present_count, 4);
        assert_eq!(c.expected_count, 5);
    }

    #[test]
    fn several_missing_ids_listed_exactly_no_percentage() {
        // The verdict names the EXACT ids, never a percentage.
        let ids = [10, 11, 14, 17, 18];
        let c = burn_contiguity("cam1", &ids);
        assert_eq!(c.missing_ids, vec![12, 13, 15, 16]);
        assert_eq!(c.expected_count, 9); // 10..=18
        assert_eq!(c.present_count, 5);
    }

    #[test]
    fn oversampled_duplicate_ids_are_not_loss() {
        // The 60→30 beat puts ONE render id on several recorded frames — the SAME
        // integer. Duplicates collapse: a contiguous set with repeats is zero loss.
        let ids = [10, 10, 11, 11, 11, 12, 13, 13, 14];
        let c = burn_contiguity("stream", &ids);
        assert!(c.is_contiguous(), "repeats of one id are not loss: {c:?}");
        assert!(c.missing_ids.is_empty());
        assert_eq!(c.present_count, 5); // distinct: 10,11,12,13,14
        assert_eq!(c.expected_count, 5);
    }

    #[test]
    fn unordered_ids_are_handled() {
        // Order is irrelevant — it is a set membership test over first..=last.
        let ids = [104, 100, 103, 101, 102];
        let c = burn_contiguity("stream", &ids);
        assert!(c.is_contiguous());
        assert_eq!(c.first_id, Some(100));
        assert_eq!(c.last_id, Some(104));
    }

    #[test]
    fn empty_sequence_is_not_a_pass() {
        // No burn rendered at all ⇒ nothing proven ⇒ must NOT read as zero loss.
        let c = burn_contiguity("stream", &[]);
        assert!(!c.is_contiguous(), "no burn ⇒ not a pass: {c:?}");
        assert_eq!(c.first_id, None);
        assert_eq!(c.present_count, 0);
    }

    #[test]
    fn single_id_is_trivially_contiguous() {
        let c = burn_contiguity("strih", &[42]);
        assert!(c.is_contiguous(), "a span of one cannot have a gap");
        assert_eq!(c.first_id, Some(42));
        assert_eq!(c.last_id, Some(42));
        assert_eq!(c.expected_count, 1);
        assert_eq!(c.missing_ids.len(), 0);
    }

    #[test]
    fn trailing_and_leading_gaps_inside_span_only() {
        // Ids outside the observed span are NOT counted — the span is what the node
        // actually rendered (first..=last). Only interior gaps are candidate drops.
        let ids = [5, 6, 7, 9, 10];
        let c = burn_contiguity("cam1", &ids);
        assert_eq!(c.missing_ids, vec![8]); // only 8 is interior; not 4, not 11
        assert_eq!(c.first_id, Some(5));
        assert_eq!(c.last_id, Some(10));
    }

    // ============================================================================
    // #198 — the IN-WINDOW contiguity check (correct for the strih/stream per-RENDER
    // burn counter, which advances faster than the emitted-frame rate).
    // ============================================================================

    fn rbf(frame_index: u64, burn_id: Option<u32>) -> RecordedBurnFrame {
        RecordedBurnFrame {
            frame_index,
            burn_id,
        }
    }

    #[test]
    fn in_window_render_tick_forward_skips_are_not_loss() {
        // THE #198 BUG: strih/stream burn id is a per-RENDER-tick counter — it advances
        // ~3x per EMITTED frame. Consecutive recorded (emitted) frames carry burn ids
        // that jump by >1 (the un-emitted render ticks). Those forward skips are NOT
        // dropped frames; every emitted frame is present, so this is ZERO loss — even
        // though the integer range (1670..28676) is 3x the frame count.
        let frames = [
            rbf(0, Some(1670)),
            rbf(1, Some(1673)),
            rbf(2, Some(1676)),
            rbf(3, Some(1679)),
            rbf(4, Some(1682)),
        ];
        let c = burn_contiguity_in_window("strih", &frames);
        assert!(
            c.is_contiguous(),
            "forward render-tick skips (counter > emit rate) are NOT loss: {c:?}"
        );
        assert!(c.missing_ids.is_empty());
        assert_eq!(c.present_count, 5);
        // expected = the count of in-window EMITTED frames, NOT the 13-wide integer span.
        assert_eq!(c.expected_count, 5);
        assert_eq!(c.first_id, Some(1670));
        assert_eq!(c.last_id, Some(1682));
    }

    #[test]
    fn out_of_window_ids_are_not_counted_only_in_window_gaps_count() {
        // The #198 TDD ask, verbatim: synthetic burn ids where some are out-of-window
        // (before the first / after the last decoded in-window frame) must NOT be counted
        // as missing; ONLY a genuine in-window gap (a delivered frame missing its burn)
        // counts. Here the caller has ALREADY trimmed the pre-/post-signal frames — the
        // out-of-window ids are simply absent from `frames`, so the range can never
        // include them. One delivered frame (index 12) carries NO burn = the one real
        // in-window drop.
        let frames = [
            rbf(10, Some(5003)), // first in-window emitted frame
            rbf(11, Some(5006)),
            rbf(12, None), // delivered frame, burn unreadable / lost = ONE real drop
            rbf(13, Some(5012)),
            rbf(14, Some(5015)), // last in-window emitted frame
        ];
        let c = burn_contiguity_in_window("stream", &frames);
        assert!(
            !c.is_contiguous(),
            "one delivered frame missing its burn is loss"
        );
        assert_eq!(c.missing_ids.len(), 1, "exactly ONE in-window drop: {c:?}");
        assert_eq!(c.present_count, 4);
        assert_eq!(c.expected_count, 5); // 5 in-window emitted frames
        assert_eq!(c.first_id, Some(5003));
        assert_eq!(c.last_id, Some(5015));
    }

    #[test]
    fn in_window_backward_jump_is_a_reorder_fault() {
        // A monotonic render counter can only ADVANCE; a burn id going backward across
        // recorded frames is reorder/corruption and MUST be counted (it can never be a
        // legitimate render-tick skip).
        let frames = [
            rbf(0, Some(100)),
            rbf(1, Some(103)),
            rbf(2, Some(101)), // backward jump (< 103) = reorder fault
            rbf(3, Some(106)),
        ];
        let c = burn_contiguity_in_window("strih", &frames);
        assert!(!c.is_contiguous(), "backward jump is a fault: {c:?}");
        assert_eq!(c.missing_ids, vec![101]);
    }

    #[test]
    fn in_window_all_frames_carry_burn_is_zero_loss() {
        // Every in-window emitted frame carries the node burn (even with big forward
        // gaps) ⇒ ZERO loss.
        let frames = [
            rbf(0, Some(2)),
            rbf(1, Some(9)),
            rbf(2, Some(15)),
            rbf(3, Some(40)),
        ];
        let c = burn_contiguity_in_window("stream", &frames);
        assert!(
            c.is_contiguous(),
            "all frames carry the burn ⇒ zero loss: {c:?}"
        );
        assert!(c.missing_ids.is_empty());
        assert_eq!(c.present_count, 4);
        assert_eq!(c.expected_count, 4);
    }

    #[test]
    fn in_window_empty_or_all_none_is_not_a_pass() {
        // No in-window delivered frame, or none carrying a burn, proves nothing ⇒ NOT zero.
        let c0 = burn_contiguity_in_window("strih", &[]);
        assert!(!c0.is_contiguous(), "empty window is not a pass: {c0:?}");
        assert_eq!(c0.first_id, None);

        let all_none = [rbf(0, None), rbf(1, None)];
        let c1 = burn_contiguity_in_window("strih", &all_none);
        assert!(!c1.is_contiguous(), "no burn ever ⇒ not a pass: {c1:?}");
        assert_eq!(c1.first_id, None);
        assert_eq!(c1.expected_count, 2);
    }

    #[test]
    fn in_window_multiple_missing_each_distinct_for_pixel_slot() {
        // Two delivered frames missing their burn ⇒ two distinct candidate drops, each
        // mapping to its own recorded slot for pixel classification.
        let frames = [
            rbf(0, Some(1000)),
            rbf(1, None), // drop 1
            rbf(2, Some(1006)),
            rbf(3, None), // drop 2
            rbf(4, Some(1012)),
        ];
        let c = burn_contiguity_in_window("strih", &frames);
        assert_eq!(
            c.missing_ids.len(),
            2,
            "two distinct in-window drops: {c:?}"
        );
        assert_eq!(c.present_count, 3);
        assert_eq!(c.expected_count, 5);
        // The synthetic candidate ids are distinct (1001 and 1007) so the verdict's
        // pixel classifier can locate each slot independently.
        assert_eq!(c.missing_ids, vec![1001, 1007]);
    }
}
