"""Tier-0 tests for issue 1342: the camboxes publish ONE NDI output, and every managed RECEIVER
queries every managed SENDER by IP, in addition to mDNS.

Three parts, all pure-bash / file-content checks (no cargo, no rig):

1. The unconsumed issue-792 `CAMn (30p)` blend stream is GONE (part 1, unchanged).
   - There is no `src/publish_30p.rs` and no wiring for it.
   - setup-device.sh REMOVES a leftover `publish-30p.conf`.
   - verify-device.sh has no `(z)` check.
2. Part 2, the revised main design: a RECEIVER-ONLY `ndi-config.v1.json`.
   - `networks.ips` is GENERATED by one pure function in `scripts/lib/ndi-discovery.sh` from the fleet
     sources of truth: `scripts/camera-set.sh` (every camera `camera_resolve` knows) and
     `scripts/lib/obs-fleet.sh` (the `ndi-sender` facet: strih-lx, stream, resolume).
   - The config carries NO `networks.discovery`. The NDI SDK (`Processing.NDI.Find.h`, `p_extra_ips`)
     queries the listed IPs IN ADDITION to mDNS, and senders never read the list. So senders keep
     announcing over mDNS, and stock TVs, guest laptops and the avahi port-map audit keep working.
   - There is no gate: receiver config is safe to ship.
   - The writers are setup-device STEP 7, setup-strih step 4b and the Windows `.ps1`. The graders are
     verify-device `(an)` and verify-strih item 34, which use the SAME generator.
3. The Discovery-Server model of part 1 is dead code and is removed: the dev1 server unit, the
   `networks.discovery` writers, the rollout gates and the server list.
"""

import json
import os
import re
import subprocess
import tempfile
import unittest

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
LIB = os.path.join(REPO, "scripts", "lib", "ndi-discovery.sh")
CAMERA_SET = os.path.join(REPO, "scripts", "camera-set.sh")
OBS_FLEET = os.path.join(REPO, "scripts", "lib", "obs-fleet.sh")
SETUP_DEVICE = os.path.join(REPO, "scripts", "setup-device.sh")
VERIFY_DEVICE = os.path.join(REPO, "scripts", "verify-device.sh")
SETUP_STRIH = os.path.join(REPO, "scripts", "setup-strih.sh")
VERIFY_STRIH = os.path.join(REPO, "scripts", "verify-strih.sh")
LAPTOP_JSON = os.path.join(REPO, "scripts", "ndi-discovery", "ndi-config.v1.json")
LAPTOP_PS1 = os.path.join(REPO, "scripts", "ndi-discovery-laptop.ps1")
DEV1_UNIT = os.path.join(REPO, "systemd", "ndi-discovery-server.service")
RULE = os.path.join(REPO, ".claude", "rules", "ndi-discovery.md")
CLAUDE_MD = os.path.join(REPO, "CLAUDE.md")

# The part-1 server address. It must never be written again, and the laptop script removes it.
RETIRED_SERVER_IP = "10.77.9.200"

# Strips every variable the tests set, so the host environment never leaks into a run.
_SCRUB = (
    "NDI_DISCOVERY_SERVERS", "NDI_DISCOVERY_ENABLED", "NDI_DISCOVERY_ENABLED_CAMBOX",
    "NDI_DISCOVERY_ENABLED_STRIH", "NDI_DISCOVERY_SYSTEM_DIR", "NDI_DISCOVERY_INTERCOM_DROPIN",
    "OBS_FLEET", "CAMERA_ACTIVE_SET", "CAMERA_SET",
)


def _read(path: str) -> str:
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def _bash(script: str, env=None) -> subprocess.CompletedProcess:
    e = dict(os.environ)
    for k in _SCRUB:
        e.pop(k, None)
    if env:
        e.update(env)
    return subprocess.run(
        ["bash", "-c", script], capture_output=True, text=True, timeout=30, cwd=REPO, env=e
    )


def _lib(body: str, env=None) -> subprocess.CompletedProcess:
    return _bash(f'set -uo pipefail\n. "{LIB}"\n{body}', env=env)


def _live_flow(path: str, guard: str) -> str:
    text = _read(path)
    pos = text.find(guard)
    assert pos >= 0, f"source-guard marker {guard!r} missing from {path}"
    return text[pos:]


def _strip_comments(text: str) -> str:
    return "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("#"))


def _expected_pinned_ips() -> list:
    """The pinned list, derived INDEPENDENTLY of the lib from the two fleet sources of truth: every
    `camN) CAMERA_IP=<ip>` arm of camera_resolve, in order, then every IPv4 host of the obs-fleet
    ndi-sender facet (retired rows excluded by obs_fleet_boxes)."""
    cams = re.findall(r"(?m)^\s*cam(\d+)\) CAMERA_IP=([0-9.]+);", _read(CAMERA_SET))
    ips = [ip for _, ip in sorted(cams, key=lambda c: int(c[0]))]
    r = _bash(f'. "{OBS_FLEET}"; obs_fleet_boxes ndi-sender')
    assert r.returncode == 0, r.stderr
    for pair in r.stdout.split():
        host = pair.split("|", 1)[1]
        if re.fullmatch(r"\d+\.\d+\.\d+\.\d+", host) and host not in ips:
            ips.append(host)
    return ips


def _pinned() -> str:
    return ",".join(_expected_pinned_ips())


# --------------------------------------------------------------------------------------------------
# Part 1 -- the 30p stream is removed end to end
# --------------------------------------------------------------------------------------------------


class ThirtyPStreamRemoved(unittest.TestCase):
    def test_publish_30p_module_is_deleted(self):
        self.assertFalse(
            os.path.exists(os.path.join(REPO, "src", "publish_30p.rs")),
            "src/publish_30p.rs must be deleted (0 consumers of CAMn (30p), issue 1342)",
        )

    def test_lib_and_main_carry_no_publish_30p_reference(self):
        for rel in ("src/lib.rs", "src/main.rs", "src/affinity.rs"):
            text = _read(os.path.join(REPO, rel))
            self.assertNotRegex(
                text, r"publish_30p|PUBLISH_30P|publish-30p", f"{rel} still references the 30p publisher"
            )

    def test_setup_device_no_longer_writes_the_30p_dropin(self):
        live = _strip_comments(_live_flow(SETUP_DEVICE, "stop here -- never run the destructive"))
        self.assertNotIn("CAMERA_BOX_PUBLISH_30P", live)
        self.assertNotRegex(live, r"cat\s*>\s*\S*publish-30p\.conf", "STEP 7 must not WRITE publish-30p.conf")

    def test_setup_device_removes_a_leftover_30p_dropin_so_live_boxes_converge(self):
        live = _strip_comments(_live_flow(SETUP_DEVICE, "stop here -- never run the destructive"))
        self.assertRegex(
            live,
            r"rm -f /etc/systemd/system/camera-box\.service\.d/publish-30p\.conf",
            "a re-provision must DELETE a leftover publish-30p.conf (the live boxes still carry it)",
        )
        rm = live.find("publish-30p.conf")
        reload = live.find("systemctl daemon-reload", rm)
        self.assertGreater(reload, rm, "the removal must happen before STEP 7's daemon-reload")

    def test_verify_device_has_no_30p_check_or_parsers(self):
        text = _read(VERIFY_DEVICE)
        for needle in ("publish_30p", "PUBLISH_30P", "publish-30p", "(30p)"):
            self.assertNotIn(needle, text, f"verify-device.sh still carries {needle!r}")
        self.assertNotRegex(text, r"(?m)^# \(z\) ", "the (z) 30p exec block must be removed")


# --------------------------------------------------------------------------------------------------
# Part 2 -- the ONE generator: networks.ips from camera-set.sh + obs-fleet.sh
# --------------------------------------------------------------------------------------------------


class Generator(unittest.TestCase):
    def test_obs_fleet_declares_the_ndi_sender_facet(self):
        r = _bash(f'. "{OBS_FLEET}"; obs_fleet_facet_members ndi-sender')
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(r.stdout.split(), ["strih-lx", "stream", "resolume"])

    def test_camera_walk_covers_every_camera_resolve_arm(self):
        r = _lib("ndi_discovery_camera_ips")
        self.assertEqual(r.returncode, 0, r.stderr)
        arms = re.findall(r"(?m)^\s*cam(\d+)\) CAMERA_IP=([0-9.]+);", _read(CAMERA_SET))
        self.assertGreaterEqual(len(arms), 7)
        self.assertEqual(r.stdout.split(), [ip for _, ip in sorted(arms, key=lambda c: int(c[0]))])

    def test_camera_walk_is_independent_of_the_active_set(self):
        # A retired-from-measurement camera is still a powered NDI sender.
        full = _lib("ndi_discovery_camera_ips").stdout
        narrow = _lib("ndi_discovery_camera_ips", env={"CAMERA_ACTIVE_SET": "cam2"}).stdout
        self.assertEqual(full, narrow)

    def test_camera_walk_never_clobbers_the_callers_resolved_camera(self):
        # setup-device STEP 7 still needs its OWN box's CAMERA_IP / CAMERA_NAME afterwards.
        r = _lib('camera_resolve cam5; ndi_discovery_camera_ips >/dev/null; echo "$CAMERA_NAME $CAMERA_IP"')
        self.assertEqual(r.stdout.strip(), "cam5 10.77.9.65", r.stderr)

    def test_pinned_list_is_every_camera_then_every_ipv4_fleet_sender(self):
        r = _lib("ndi_discovery_sender_ips pinned")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(r.stdout.strip(), _pinned())
        got = r.stdout.strip().split(",")
        for ip in ("10.77.9.61", "10.77.9.67", "10.77.9.202", "10.77.9.204"):
            self.assertIn(ip, got)
        self.assertNotIn("10.77.9.182", got, "the retired imag row must not be listed")
        self.assertFalse(any(not re.fullmatch(r"\d+\.\d+\.\d+\.\d+", x) for x in got), got)

    def test_resolve_mode_appends_the_resolved_hostname_sender(self):
        stub = 'ndi_discovery_resolve_ipv4() { [ "$1" = resolume.lan ] && printf "10.77.9.201\\n"; return 0; }'
        r = _lib(f"{stub}\nndi_discovery_sender_ips")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(r.stdout.strip(), _pinned() + ",10.77.9.201")

    def test_unresolvable_hostname_is_skipped_and_named(self):
        stub = "ndi_discovery_resolve_ipv4() { return 0; }"
        r = _lib(f"{stub}\nndi_discovery_sender_ips")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(r.stdout.strip(), _pinned())
        self.assertIn("resolume.lan", r.stderr, "the skipped traveling sender must be named")

    def test_a_non_ipv4_resolution_is_rejected(self):
        stub = 'ndi_discovery_resolve_ipv4() { printf "fe80::1\\n"; }'
        r = _lib(f"{stub}\nndi_discovery_sender_ips")
        self.assertEqual(r.stdout.strip(), _pinned())

    def test_duplicates_are_listed_once(self):
        fleet = "strih-lx|10.77.9.61|linux-genlock|always\nstream|10.77.9.204|windows-genlock|always\nresolume|10.77.9.204|windows-genlock|traveling"
        r = _lib("ndi_discovery_sender_ips pinned", env={"OBS_FLEET": fleet})
        ips = r.stdout.strip().split(",")
        self.assertEqual(len(ips), len(set(ips)), ips)
        self.assertEqual(ips[-1], "10.77.9.204")

    def test_a_fleet_lookup_failure_is_loud(self):
        r = _lib('ndi_discovery_sender_ips pinned; echo "rc=$?"', env={"OBS_FLEET": "stream|10.77.9.204|windows-genlock|always"})
        self.assertIn("rc=1", r.stdout, "a facet naming a box absent from OBS_FLEET must fail, never write a short list")


# --------------------------------------------------------------------------------------------------
# Part 2 -- the receiver-only config, its grader and its writer
# --------------------------------------------------------------------------------------------------


class ReceiverConfig(unittest.TestCase):
    def test_config_json_is_receiver_only(self):
        r = _lib("ndi_discovery_config_json")
        self.assertEqual(r.returncode, 0, r.stderr)
        doc = json.loads(r.stdout)
        self.assertEqual(doc, {"ndi": {"networks": {"ips": _pinned()}}})
        self.assertNotIn("discovery", r.stdout)
        self.assertTrue(r.stdout.endswith("}\n"))
        self.assertFalse(r.stdout.startswith(chr(0xFEFF)), "never a BOM")

    def test_config_json_takes_an_explicit_list(self):
        r = _lib('ndi_discovery_config_json "10.0.0.1,10.0.0.2"')
        self.assertEqual(json.loads(r.stdout)["ndi"]["networks"]["ips"], "10.0.0.1,10.0.0.2")

    def test_parsers(self):
        text = '{"ndi": {"networks": {"ips": "10.77.9.61, 10.77.9.62", "discovery": "10.77.9.200"}}}'
        r = _lib(f"T='{text}'; ndi_discovery_config_ips \"$T\"; ndi_discovery_config_servers \"$T\"")
        self.assertEqual(r.stdout.splitlines(), ["10.77.9.61, 10.77.9.62", RETIRED_SERVER_IP])

    def test_verdict_ok_on_the_rendered_config(self):
        r = _lib('ndi_discovery_config_verdict "$(ndi_discovery_config_json)"')
        self.assertEqual(r.stdout.strip(), "ok", r.stdout + r.stderr)

    def test_verdict_accepts_extras_spaces_and_any_order(self):
        ips = list(reversed(_expected_pinned_ips())) + ["10.77.9.201"]
        text = json.dumps({"ndi": {"networks": {"ips": ", ".join(ips)}}})
        r = _lib(f"ndi_discovery_config_verdict '{text}'")
        self.assertEqual(r.stdout.strip(), "ok", r.stdout)

    def test_verdict_fails_each_facet(self):
        pinned = _pinned()
        short = ",".join(_expected_pinned_ips()[1:])
        cases = {
            "": "missing",
            '{"ndi":{"networks":{"ips":"' + pinned + '"}}': "JSON",
            json.dumps({"ndi": {"networks": {"ips": pinned, "discovery": RETIRED_SERVER_IP}}}): "discovery",
            json.dumps({"ndi": {"networks": {"ips": short}}}): _expected_pinned_ips()[0],
            json.dumps({"ndi": {"networks": {"ips": ""}}}): "ips",
        }
        for text, facet in cases.items():
            r = _lib(f"ndi_discovery_config_verdict '{text}'")
            self.assertEqual(r.returncode, 0, r.stderr)
            self.assertTrue(r.stdout.startswith("FAIL:"), f"{text!r} must FAIL, got {r.stdout!r}")
            self.assertIn(facet, r.stdout, f"{text!r} verdict must name {facet!r}: {r.stdout!r}")

    def test_verdict_grades_against_an_explicit_required_list(self):
        text = json.dumps({"ndi": {"networks": {"ips": "10.0.0.1"}}})
        self.assertEqual(_lib(f"ndi_discovery_config_verdict '{text}' 10.0.0.1").stdout.strip(), "ok")
        self.assertTrue(_lib(f"ndi_discovery_config_verdict '{text}' 10.0.0.1,10.0.0.2").stdout.startswith("FAIL:"))

    def test_dropin_points_the_service_at_the_system_config_dir(self):
        r = _lib('ndi_discovery_dropin_content; printf "DIR=%s\\n" "$(ndi_discovery_dropin_config_dir "$(ndi_discovery_dropin_content)")"')
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertRegex(r.stdout, r"(?m)^\[Service\]$")
        self.assertRegex(r.stdout, r"(?m)^Environment=NDI_CONFIG_DIR=/etc/ndi$")
        self.assertIn("DIR=/etc/ndi", r.stdout)
        self.assertNotIn("Discovery Server", r.stdout)

    def test_dropin_parser_empty_when_absent(self):
        r = _lib("ndi_discovery_dropin_config_dir ''; echo \"rc=$?\"")
        self.assertEqual(r.stdout.strip(), "rc=0")


class Writer(unittest.TestCase):
    def test_writes_the_rendered_file_idempotently(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = os.path.join(tmp, "a", ".ndi")
            for _ in range(2):
                r = _lib(f'ndi_discovery_write_config "{target}" "$(ndi_discovery_sender_ips pinned)"')
                self.assertEqual(r.returncode, 0, r.stderr)
            path = os.path.join(target, "ndi-config.v1.json")
            self.assertEqual(_read(path), _lib("ndi_discovery_config_json").stdout)
            self.assertEqual(oct(os.stat(path).st_mode & 0o777), "0o644")
            self.assertEqual(os.listdir(target), ["ndi-config.v1.json"], "no temp file / backup left behind")

    def test_merge_keeps_other_keys_sets_ips_and_drops_a_discovery_server(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "ndi-config.v1.json")
            with open(path, "w") as fh:
                fh.write('{"ndi": {"groups": {"recv": "Public"}, "networks": {"ips": "10.77.8.51", "discovery": "10.77.9.200"}}, "other": 1}')
            r = _lib(f'ndi_discovery_write_config "{tmp}" "10.0.0.1,10.0.0.2"')
            self.assertEqual(r.returncode, 0, r.stderr)
            doc = json.loads(_read(path))
            self.assertEqual(doc["ndi"]["groups"], {"recv": "Public"})
            self.assertEqual(doc["other"], 1)
            self.assertEqual(doc["ndi"]["networks"], {"ips": "10.0.0.1,10.0.0.2"},
                             "a managed box never keeps a discovery server (it would silence its senders' mDNS)")

    def test_unparseable_existing_config_is_backed_up_then_replaced(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "ndi-config.v1.json")
            with open(path, "w") as fh:
                fh.write("{not json")
            r = _lib(f'ndi_discovery_write_config "{tmp}" "10.0.0.1"')
            self.assertEqual(r.returncode, 0, r.stderr)
            self.assertEqual(_read(path), _lib('ndi_discovery_config_json "10.0.0.1"').stdout)
            baks = [f for f in os.listdir(tmp) if f.startswith("ndi-config.v1.json.bak-")]
            self.assertEqual(len(baks), 1, os.listdir(tmp))
            self.assertEqual(_read(os.path.join(tmp, baks[0])), "{not json")

    def test_an_empty_list_is_refused(self):
        with tempfile.TemporaryDirectory() as tmp:
            r = _lib(f'ndi_discovery_write_config "{tmp}" ""; echo "rc=$?"')
            self.assertNotIn("rc=0", r.stdout)
            self.assertEqual(os.listdir(tmp), [])

    def test_fails_loud_on_an_unwritable_dir(self):
        r = _lib('ndi_discovery_write_config "/proc/ndi-discovery-cannot-exist" "10.0.0.1"; echo "rc=$?"')
        self.assertNotIn("rc=0", r.stdout)


class Cli(unittest.TestCase):
    def test_pinned_json_and_ips(self):
        r = _bash(f'bash "{LIB}" --json pinned')
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(r.stdout, _lib("ndi_discovery_config_json").stdout)
        r = _bash(f'bash "{LIB}" --ips pinned')
        self.assertEqual(r.stdout.strip(), _pinned())

    def test_unknown_argument_is_an_error(self):
        self.assertNotEqual(_bash(f'bash "{LIB}" --bogus').returncode, 0)


# --------------------------------------------------------------------------------------------------
# Part 2 -- provisioning + grading wiring (no gates)
# --------------------------------------------------------------------------------------------------


class CamboxWiring(unittest.TestCase):
    def test_setup_device_writes_config_and_dropin_in_step_7_ungated(self):
        text = _read(SETUP_DEVICE)
        self.assertRegex(text, r'(?m)^\. "\$HERE/lib/ndi-discovery\.sh"')
        live = _strip_comments(_live_flow(SETUP_DEVICE, "stop here -- never run the destructive"))
        gen = live.find('NDI_IPS="$(ndi_discovery_sender_ips)"')
        write = live.find('ndi_discovery_write_config "$NDI_DISCOVERY_SYSTEM_DIR" "$NDI_IPS"')
        dropin = live.find('ndi_discovery_dropin_content > "$NDI_DISCOVERY_CAMBOX_DROPIN"')
        self.assertTrue(0 <= gen < write, "STEP 7 generates the list, then writes /etc/ndi/ndi-config.v1.json")
        self.assertGreaterEqual(dropin, 0, "STEP 7 must write the camera-box NDI_CONFIG_DIR drop-in")
        reload = live.find("systemctl daemon-reload", max(write, dropin))
        step8 = live.find("[8/${TOTAL_STEPS}]")
        self.assertTrue(0 <= reload < step8, "both writes sit inside STEP 7, before its daemon-reload")
        self.assertNotIn("ndi_discovery_enabled", live, "no rollout gate: receiver config ships ungated")

    def test_verify_device_an_grades_against_the_generator(self):
        text = _read(VERIFY_DEVICE)
        self.assertRegex(text, r'(?m)^\. "\$HERE/lib/ndi-discovery\.sh"')
        self.assertGreaterEqual(len(re.findall(r"\(an\) NDI discovery", text)), 3, "header + usage + exec block")
        an = text.find("# (an) NDI discovery")
        q = text.rfind("# (q) .bak cruft drift")
        self.assertTrue(0 <= an < q, "(an) must sit BEFORE (q), which stays the last check")
        block = text[an:q]
        self.assertIn('NDI_DISC_REQUIRED="$(ndi_discovery_sender_ips pinned)"', block)
        self.assertIn('ndi_discovery_config_verdict "$NDI_DISC_CONF" "$NDI_DISC_REQUIRED"', block)
        self.assertIn("ndi_discovery_dropin_config_dir", block)
        self.assertIn("fail ", block)
        self.assertNotIn('warn "', block)
        self.assertNotIn("rollout_pending", block)


class StrihWiring(unittest.TestCase):
    def test_setup_strih_writes_both_configs_and_the_intercom_dropin_ungated(self):
        text = _read(SETUP_STRIH)
        self.assertRegex(text, r'(?m)^\. "\$\{HERE\}/lib/ndi-discovery\.sh"')
        code = _strip_comments(text)
        gen = code.find('NDI_IPS="$(ndi_discovery_sender_ips)"')
        user = code.find('ndi_discovery_write_config "${USER_HOME}/.ndi" "$NDI_IPS" "$DESKTOP_USER"')
        system = code.find('ndi_discovery_write_config "$NDI_DISCOVERY_SYSTEM_DIR" "$NDI_IPS"')
        dropin = code.find('ndi_discovery_dropin_content > "$NDI_DISCOVERY_INTERCOM_DROPIN"')
        self.assertTrue(0 <= gen < user < system < dropin, (gen, user, system, dropin))
        self.assertNotIn("ndi_discovery_enabled", code)

    def test_item_34_sits_before_item_32_and_33_stays_last(self):
        text = _read(VERIFY_STRIH)
        self.assertRegex(text, r'(?m)^\. "\$\{HERE\}/lib/ndi-discovery\.sh"')
        item = text.find("# 34) NDI discovery")
        self.assertGreaterEqual(item, 0)
        end = text.find("\n# 32) the shared OBS-box appliance baseline", item)
        self.assertGreater(end, item, "item 34 must sit before item 32")
        self.assertGreater(text.find("# 33) NO realtime-priority grant"), end, "item 33 stays the last item")
        block = text[item:end]
        self.assertIn("ndi_discovery_sender_ips pinned", block)
        self.assertIn("ndi_discovery_config_verdict", block)
        self.assertNotIn("rollout_pending", block)


class VerifyStrihItem34Behaviour(unittest.TestCase):
    """Run the REAL item-34 block (sliced from verify-strih.sh) against temp dirs."""

    def _run(self, tmp):
        text = _read(VERIFY_STRIH)
        item = text.find("# 34) NDI discovery")
        block = text[item:text.find("\n# 32) the shared OBS-box", item)]
        prelude = 'FAILS=0\nok() { echo "PASS $1"; }\nbad() { echo "FAIL $1"; FAILS=$((FAILS+1)); }\nnote() { echo "NOTE $1"; }\n'
        env = {
            "NDI_DISCOVERY_SYSTEM_DIR": os.path.join(tmp, "etc-ndi"),
            "NDI_DISCOVERY_INTERCOM_DROPIN": os.path.join(tmp, "intercom-ndi-discovery.conf"),
        }
        script = f'set -euo pipefail\n. "{LIB}"\nUSER_HOME="{tmp}/home"\n{prelude}{block}\necho "FAILS=$FAILS"'
        return _bash(script, env=env)

    def _configure(self, tmp, ips=None):
        env = {"NDI_DISCOVERY_SYSTEM_DIR": os.path.join(tmp, "etc-ndi")}
        lst = ips if ips is not None else _pinned()
        for d in (f"{tmp}/home/.ndi", "$NDI_DISCOVERY_SYSTEM_DIR"):
            self.assertEqual(_lib(f'ndi_discovery_write_config "{d}" "{lst}"', env=env).returncode, 0)
        with open(os.path.join(tmp, "intercom-ndi-discovery.conf"), "w") as fh:
            fh.write(_lib("ndi_discovery_dropin_content", env=env).stdout)

    def test_unconfigured_box_fails_every_facet(self):
        with tempfile.TemporaryDirectory() as tmp:
            r = self._run(tmp)
            self.assertEqual(r.returncode, 0, r.stderr)
            self.assertIn("FAILS=3", r.stdout, r.stdout)

    def test_fully_configured_box_passes(self):
        with tempfile.TemporaryDirectory() as tmp:
            self._configure(tmp)
            r = self._run(tmp)
            self.assertEqual(r.returncode, 0, r.stderr)
            self.assertIn("FAILS=0", r.stdout, r.stdout)
            self.assertEqual(r.stdout.count("PASS (ndi-discovery)"), 3, r.stdout)

    def test_a_renumbered_sender_fails_until_re_provisioned(self):
        with tempfile.TemporaryDirectory() as tmp:
            self._configure(tmp, ips=",".join(_expected_pinned_ips()[:-1]))
            r = self._run(tmp)
            self.assertIn("FAILS=2", r.stdout, r.stdout)
            self.assertIn(_expected_pinned_ips()[-1], r.stdout)


# --------------------------------------------------------------------------------------------------
# Part 2 -- checked-in config (stream / resolume / Linux laptop) + the Windows laptop script
# --------------------------------------------------------------------------------------------------


class CheckedInConfig(unittest.TestCase):
    def test_checked_in_config_is_byte_identical_to_the_generator(self):
        with open(LAPTOP_JSON, "rb") as fh:
            raw = fh.read()
        self.assertFalse(raw.startswith(b"\xef\xbb\xbf"), "no UTF-8 BOM")
        self.assertEqual(raw.decode("utf-8"), _lib("ndi_discovery_config_json").stdout)
        self.assertNotIn(b"discovery", raw)


class LaptopScript(unittest.TestCase):
    def test_ps1_default_list_is_the_generator_output(self):
        text = _read(LAPTOP_PS1)
        m = re.search(r"\[string\]\$Ips\s*=\s*'([^']+)'", text)
        self.assertIsNotNone(m, "the -Ips parameter needs a literal default")
        self.assertEqual(m.group(1), _pinned(), "the .ps1 default must equal `ndi-discovery.sh --ips pinned`")

    def test_ps1_merges_backs_up_and_writes_without_a_bom(self):
        text = _read(LAPTOP_PS1)
        self.assertIn("$ErrorActionPreference = 'Stop'", text)
        self.assertIn("ProgramData", text)
        self.assertIn("ndi-config.v1.json", text)
        self.assertIn("ConvertFrom-Json", text, "an existing config is merged, not clobbered")
        self.assertIn(".bak-", text, "the old config is backed up next to it")
        self.assertIn("UTF8Encoding($false)", text, "BOM-free writer (the dantesync BOM incident)")
        self.assertIn("[System.IO.File]::WriteAllText", text)
        self.assertNotRegex(text, r"(?i)\b(Set-Content|Out-File|Add-Content)\b", "these write a BOM on PS 5.1")
        self.assertIn("-DryRun", text)
        self.assertIn("$null -eq $obj.$name", text, '"ndi": null must be replaced, not dereferenced')

    def test_ps1_is_receiver_only(self):
        code = "\n".join(l for l in _read(LAPTOP_PS1).splitlines() if not l.lstrip().startswith("#"))
        self.assertNotRegex(code, r"\$net\.discovery\s*=", "the laptop script never SETS a discovery server")
        self.assertIn(f"'{RETIRED_SERVER_IP}'", code, "it removes the retired part-1 server value")
        self.assertIn("Properties.Remove('discovery')", code)


# --------------------------------------------------------------------------------------------------
# Part 3 -- the Discovery-Server model is dead code
# --------------------------------------------------------------------------------------------------


class ServerModelRemoved(unittest.TestCase):
    def test_server_unit_is_deleted(self):
        self.assertFalse(os.path.exists(DEV1_UNIT))

    def test_no_script_carries_the_server_or_its_gates(self):
        for path in (LIB, SETUP_DEVICE, VERIFY_DEVICE, SETUP_STRIH, VERIFY_STRIH):
            code = _strip_comments(_read(path))
            for needle in ("NDI_DISCOVERY_SERVERS", "NDI_DISCOVERY_ENABLED", "rollout_pending",
                           "ndi-discovery-server", "ndi_discovery_enabled"):
                self.assertNotIn(needle, code, f"{path} still carries {needle!r}")

    def test_lib_never_writes_a_discovery_key(self):
        code = _strip_comments(_read(LIB))
        self.assertNotRegex(code, r'\\"discovery\\":\s*\\"%s', "the renderer must not emit networks.discovery")
        self.assertNotRegex(code, r'net\["discovery"\]\s*=', "the merger must not SET networks.discovery")


class Rule(unittest.TestCase):
    def test_rule_paths_and_router_line(self):
        text = _read(RULE)
        self.assertTrue(text.startswith("---\npaths:\n"), "path-scoped rule")
        front = text.split("---", 2)[1]
        for p in ("scripts/lib/ndi-discovery.sh", "scripts/ndi-discovery-laptop.ps1", "scripts/ndi-discovery/**",
                  "scripts/camera-set.sh", "scripts/lib/obs-fleet.sh", "scripts/verify-strih.sh"):
            self.assertIn(p, front)
        self.assertNotIn("ndi-discovery-server", front)
        router = [l for l in _read(CLAUDE_MD).splitlines() if ".claude/rules/ndi-discovery.md" in l]
        self.assertEqual(len(router), 1)
        self.assertIn("networks.ips", router[0])
        self.assertNotIn("NDI_DISCOVERY_ENABLED", router[0])

    def test_rule_states_the_sdk_contract_and_the_supervisor_steps(self):
        text = _read(RULE)
        for needle in ("p_extra_ips", "When none is specified the registry is used", "mDNS",
                       "Senders, however, will avoid using mDNS", "stock", "--ips", "Rollback"):
            self.assertIn(needle, text)


if __name__ == "__main__":
    unittest.main()
