//! The hub's HTTP layer (issue 1345): the observability API + the embedded phone PWA (M3b).
//!
//! `/api/state` returns the whole [`HubState`] JSON; `/ws` pushes a fresh snapshot every ~1 s from
//! a single background pump (all clients fan out from one `watch` channel); `/api/version` is the
//! version-on-dashboard surface. `/` and the static asset routes serve the Interkom phone PWA
//! (`intercom/web/`), embedded via `include_str!`/`include_bytes!` so the hub binary is
//! self-contained on strih-lx (the same model bkshading uses). The vendored `janus.js` (MIT) drives
//! the WebRTC audio; the picture is the MJPEG route M3c (issue 1347) will add.

use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use axum::{
    body::{Body, Bytes},
    extract::{
        ws::{Message, WebSocket, WebSocketUpgrade},
        State,
    },
    http::{header, HeaderName, StatusCode},
    response::{Html, IntoResponse, Json, Response},
    routing::get,
    Router,
};
use tokio::sync::{mpsc, watch};
use tokio_stream::wrappers::ReceiverStream;

use crate::ndi_video::VideoState;
use crate::state::HubState;

// issue 1345 M3c: the Interkom MJPEG picture. `/interkom.mjpeg` streams `multipart/x-mixed-replace`
// parts as new frames arrive; `/interkom.jpg` returns the single latest frame (a curl-able liveness
// check). The picture frames come from the NDI receiver in `ndi_video`.
/// The multipart MIME + boundary the MJPEG stream uses (the `<img>` MJPEG contract the PWA reads).
pub const MJPEG_CONTENT_TYPE: &str = "multipart/x-mixed-replace; boundary=frame";
/// A client with no NEW frame for longer than this gets the stream ENDED (so the PWA's `<img>`
/// `onerror` placeholder + retry kicks in) — never a hung connection.
pub const MJPEG_MAX_AGE_MS: u64 = 5000;

const VERSION: &str = env!("CARGO_PKG_VERSION");

// issue 1345 M3b: the Interkom phone PWA, embedded so the hub binary stays self-contained on
// strih-lx (same include_str!/include_bytes! model as bkshading). The relative paths resolve from
// `intercom/hub/src/` → `intercom/web/`. `janus.js` is vendored (MIT, tag v1.1.2 — see
// intercom/web/VENDORED.md); the icons are generated by intercom/web/gen-icons.py (stdlib, no dep).
const INDEX_HTML: &str = include_str!("../../web/index.html");
const APP_JS: &str = include_str!("../../web/app.js");
const STYLE_CSS: &str = include_str!("../../web/style.css");
const JANUS_JS: &str = include_str!("../../web/janus.js");
const MANIFEST_JSON: &str = include_str!("../../web/manifest.webmanifest");
const SW_JS: &str = include_str!("../../web/sw.js");
const ICON_192_PNG: &[u8] = include_bytes!("../../web/icon-192.png");
const ICON_512_PNG: &[u8] = include_bytes!("../../web/icon-512.png");
const FAVICON_SVG: &str = include_str!("../../web/favicon.svg");

// The Content-Type each PWA asset route serves, exposed so the route tests can pin the exact type
// without standing up an HTTP server (mirrors bkshading's `*_CONTENT_TYPE`).
pub const APP_JS_CONTENT_TYPE: &str = "text/javascript; charset=utf-8";
pub const STYLE_CSS_CONTENT_TYPE: &str = "text/css; charset=utf-8";
pub const JS_CONTENT_TYPE: &str = "text/javascript; charset=utf-8";
pub const MANIFEST_CONTENT_TYPE: &str = "application/manifest+json";
pub const SW_JS_CONTENT_TYPE: &str = "text/javascript; charset=utf-8";
pub const PNG_CONTENT_TYPE: &str = "image/png";
pub const SVG_CONTENT_TYPE: &str = "image/svg+xml";

/// The compiled hub version (the version-on-dashboard surface); exposed for the route tests.
pub fn pkg_version() -> &'static str {
    VERSION
}

/// The served PWA index with the version placeholder substituted (read straight from the DOM).
pub fn rendered_index() -> String {
    INDEX_HTML.replace("{{VERSION}}", VERSION)
}
/// The embedded phone app JS (issue 1345 M3b).
pub fn app_js_asset() -> &'static str {
    APP_JS
}
/// The embedded stylesheet.
pub fn style_css_asset() -> &'static str {
    STYLE_CSS
}
/// The vendored janus.js WebRTC library (MIT, tag v1.1.2).
pub fn janus_js_asset() -> &'static str {
    JANUS_JS
}
/// The embedded PWA manifest JSON.
pub fn manifest_asset() -> &'static str {
    MANIFEST_JSON
}
/// The embedded service worker JS (pure passthrough, no cache).
pub fn sw_js_asset() -> &'static str {
    SW_JS
}
/// The embedded 192px PWA icon PNG bytes.
pub fn icon_192_asset() -> &'static [u8] {
    ICON_192_PNG
}
/// The embedded 512px PWA icon PNG bytes.
pub fn icon_512_asset() -> &'static [u8] {
    ICON_512_PNG
}
/// The embedded SVG favicon.
pub fn favicon_svg_asset() -> &'static str {
    FAVICON_SVG
}

#[derive(Clone)]
pub struct AppState {
    /// The latest hub state, published by the block-status pump. Keeping a receiver here means the
    /// pump's `send` never fails for "no receivers".
    pub live: watch::Receiver<Arc<HubState>>,
    /// The Interkom picture slot (issue 1345 M3c), present only when the hub has a `[video]` config.
    /// `/interkom.mjpeg` + `/interkom.jpg` serve from it; `None` → those routes report 503.
    pub video: Option<Arc<VideoState>>,
}

pub fn router(state: AppState) -> Router {
    Router::new()
        .route("/", get(index))
        .route("/app.js", get(app_js))
        .route("/style.css", get(style_css))
        .route("/janus.js", get(janus_js))
        .route("/manifest.webmanifest", get(manifest))
        .route("/sw.js", get(service_worker))
        .route("/icon-192.png", get(icon_192))
        .route("/icon-512.png", get(icon_512))
        .route("/favicon.svg", get(favicon_svg))
        .route("/api/version", get(version))
        .route("/api/state", get(api_state))
        .route("/interkom.mjpeg", get(interkom_mjpeg))
        .route("/interkom.jpg", get(interkom_jpg))
        .route("/ws", get(ws_upgrade))
        .with_state(state)
}

/// The Interkom phone PWA index (issue 1345 M3b — replaces the M1 plain-text liveness page).
async fn index() -> Html<String> {
    Html(rendered_index())
}

async fn app_js() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, APP_JS_CONTENT_TYPE)], APP_JS)
}

async fn style_css() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, STYLE_CSS_CONTENT_TYPE)], STYLE_CSS)
}

async fn janus_js() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, JS_CONTENT_TYPE)], JANUS_JS)
}

async fn manifest() -> impl IntoResponse {
    (
        [(header::CONTENT_TYPE, MANIFEST_CONTENT_TYPE)],
        MANIFEST_JSON,
    )
}

async fn service_worker() -> impl IntoResponse {
    (
        [
            (header::CONTENT_TYPE, SW_JS_CONTENT_TYPE),
            // Allow the SW to control the whole origin even though it is served from /sw.js.
            (HeaderName::from_static("service-worker-allowed"), "/"),
        ],
        SW_JS,
    )
}

async fn icon_192() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, PNG_CONTENT_TYPE)], ICON_192_PNG)
}

async fn icon_512() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, PNG_CONTENT_TYPE)], ICON_512_PNG)
}

async fn favicon_svg() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, SVG_CONTENT_TYPE)], FAVICON_SVG)
}

async fn version() -> Json<serde_json::Value> {
    Json(serde_json::json!({ "version": VERSION }))
}

async fn api_state(State(state): State<AppState>) -> Json<Arc<HubState>> {
    Json(state.live.borrow().clone())
}

async fn ws_upgrade(State(state): State<AppState>, ws: WebSocketUpgrade) -> Response {
    ws.on_upgrade(move |socket| ws_push(socket, state.live.clone()))
}

/// Push the latest [`HubState`] to one client: the current state immediately, then a fresh state on
/// every pump update. Push-only (a browser panel sends nothing); the loop ends when the client goes
/// away or the pump is dropped (shutdown).
async fn ws_push(mut socket: WebSocket, mut rx: watch::Receiver<Arc<HubState>>) {
    loop {
        let snapshot = rx.borrow_and_update().clone();
        match ws_encode(&snapshot) {
            Ok(text) => {
                if socket.send(Message::Text(text)).await.is_err() {
                    break;
                }
            }
            Err(e) => {
                tracing::warn!(error = %e, "ws: serialize hub state failed");
                break;
            }
        }
        if rx.changed().await.is_err() {
            break;
        }
    }
}

/// Serialize a hub state for the WS wire (the exact text a `/ws` frame carries).
pub fn ws_encode(state: &HubState) -> Result<String, serde_json::Error> {
    serde_json::to_string(state)
}

// --- The Interkom MJPEG picture (issue 1345 M3c) ---------------------------------------------

/// One `multipart/x-mixed-replace` part: `--frame\r\nContent-Type: image/jpeg\r\nContent-Length:
/// N\r\n\r\n<jpeg>\r\n`. Pure so the exact framing bytes are unit-tested without a server.
pub fn mjpeg_part(jpeg: &[u8]) -> Vec<u8> {
    let header = format!(
        "--frame\r\nContent-Type: image/jpeg\r\nContent-Length: {}\r\n\r\n",
        jpeg.len()
    );
    let mut out = Vec::with_capacity(header.len() + jpeg.len() + 2);
    out.extend_from_slice(header.as_bytes());
    out.extend_from_slice(jpeg);
    out.extend_from_slice(b"\r\n");
    out
}

/// Whether the latest frame is older than `max_age_ms`. A backwards clock (`now < updated`) saturates
/// to age 0 → never stale. Pure so the >5 s stream-ends boundary is unit-tested.
pub fn frame_is_stale(updated_ms: u64, now_ms: u64, max_age_ms: u64) -> bool {
    now_ms.saturating_sub(updated_ms) > max_age_ms
}

/// Wall-clock ms (for the MJPEG stale check).
fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// The MJPEG slot poll cadence for a target `fps` (~fps × 2, clamped 10..=500 ms, never a busy-loop).
fn mjpeg_poll_interval(target_fps: u32) -> Duration {
    let ms = (500 / target_fps.max(1)).clamp(10, 500);
    Duration::from_millis(ms as u64)
}

/// `GET /interkom.mjpeg` — stream `multipart/x-mixed-replace` parts as the slot's frame counter
/// advances (poll ~fps × 2, never a busy-loop). A client with no new frame for > 5 s gets the stream
/// ENDED so the PWA's `<img>` `onerror` placeholder + retry kicks in. 503 when video is disabled.
async fn interkom_mjpeg(State(state): State<AppState>) -> Response {
    let Some(video) = state.video.clone() else {
        return (StatusCode::SERVICE_UNAVAILABLE, "interkom video disabled").into_response();
    };
    let (tx, rx) = mpsc::channel::<Result<Bytes, std::io::Error>>(4);
    tokio::spawn(mjpeg_pump(video, tx));
    let body = Body::from_stream(ReceiverStream::new(rx));
    (
        [
            (header::CONTENT_TYPE, MJPEG_CONTENT_TYPE),
            (header::CACHE_CONTROL, "no-store"),
        ],
        body,
    )
        .into_response()
}

/// Push MJPEG parts to one client: on every poll, send a new part iff the slot's counter advanced;
/// end (drop the sender → stream closes) once no new frame has arrived for [`MJPEG_MAX_AGE_MS`]. Ends
/// immediately when the client disconnects (a failed `send`).
async fn mjpeg_pump(video: Arc<VideoState>, tx: mpsc::Sender<Result<Bytes, std::io::Error>>) {
    let poll = mjpeg_poll_interval(video.target_fps());
    let mut last_sent: Option<u64> = None;
    // Reference time for the stale check: the connection start, then each frame we send. A client
    // therefore waits up to MJPEG_MAX_AGE_MS for the FIRST frame before the stream ends.
    let mut last_activity = now_ms();
    loop {
        tokio::time::sleep(poll).await;
        let now = now_ms();
        // Read the frame + its counter as ONE paired snapshot (VideoState::latest) so the counter we
        // record always matches the frame we sent — avoids re-sending a frame as a duplicate part.
        if let Some((jpeg, counter)) = video.latest() {
            if last_sent != Some(counter) {
                if tx.send(Ok(Bytes::from(mjpeg_part(&jpeg)))).await.is_err() {
                    return; // client gone
                }
                last_sent = Some(counter);
                last_activity = now;
                continue;
            }
        }
        if frame_is_stale(last_activity, now, MJPEG_MAX_AGE_MS) {
            return; // no new frame for > 5 s → end the stream (PWA onerror + retry)
        }
    }
}

/// `GET /interkom.jpg` — the latest single JPEG frame (200), or 503 with a short text body when there
/// is no frame yet / video is disabled. A curl-able liveness check.
async fn interkom_jpg(State(state): State<AppState>) -> Response {
    match state.video.as_ref().and_then(|v| v.latest_frame()) {
        Some(jpeg) => (
            [
                (header::CONTENT_TYPE, "image/jpeg"),
                (header::CACHE_CONTROL, "no-store"),
            ],
            (*jpeg).clone(),
        )
            .into_response(),
        None if state.video.is_some() => {
            (StatusCode::SERVICE_UNAVAILABLE, "no interkom frame yet").into_response()
        }
        None => (StatusCode::SERVICE_UNAVAILABLE, "interkom video disabled").into_response(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::matrix::Matrix;
    use crate::state::{HubState, RuntimeStats};

    fn hub_state() -> HubState {
        let m = Matrix::from_toml(
            r#"
[hub]
bind = "0.0.0.0:8790"
vban_bind = "0.0.0.0:6980"
sample_rate = 48000
block_frames = 256

[[participant]]
name = "cam1"
role = "cambox"
adapter = "vban"
host = "cam1.lan"
in_stream = "cam1"
out_stream = "cam1"
in_channels = 2
out_channels = 2
"#,
        )
        .unwrap();
        HubState::snapshot(&m, "1.7.0-test", &[RuntimeStats::default()])
    }

    #[test]
    fn ws_encode_is_the_state_json() {
        let hs = hub_state();
        let text = ws_encode(&hs).unwrap();
        let v: serde_json::Value = serde_json::from_str(&text).unwrap();
        assert_eq!(v["version"], "1.7.0-test");
        assert_eq!(v["participants"][0]["name"], "cam1");
    }

    #[test]
    fn version_constant_is_populated() {
        assert!(!VERSION.is_empty());
    }

    #[test]
    fn index_is_the_pwa_not_the_m1_text_page() {
        // M3b: `/` now serves the installable PWA (the M1 plain-text page is gone), with the
        // version placeholder substituted for the DOM.
        let html = rendered_index();
        assert!(
            !html.contains("{{VERSION}}"),
            "version placeholder substituted"
        );
        assert!(html.contains("<!DOCTYPE html>"), "index is the PWA HTML");
        assert!(
            html.contains("data-role=\"connect\""),
            "the connect gesture button"
        );
        assert!(
            html.contains("/manifest.webmanifest"),
            "the PWA manifest is linked"
        );
    }
}
