//! The hub's HTTP layer (issue 1345): the observability API + the embedded phone PWA (M3b).
//!
//! `/api/state` returns the whole [`HubState`] JSON; `/ws` pushes a fresh snapshot every ~1 s from
//! a single background pump (all clients fan out from one `watch` channel); `/api/version` is the
//! version-on-dashboard surface. `/` and the static asset routes serve the Interkom phone PWA
//! (`intercom/web/`), embedded via `include_str!`/`include_bytes!` so the hub binary is
//! self-contained on strih-lx (the same model bkshading uses). The vendored `janus.js` (MIT) drives
//! the WebRTC audio; the picture is the MJPEG route M3c (issue 1347) will add.

use std::sync::Arc;

use axum::{
    extract::{
        ws::{Message, WebSocket, WebSocketUpgrade},
        State,
    },
    http::{header, HeaderName},
    response::{Html, IntoResponse, Json, Response},
    routing::get,
    Router,
};
use tokio::sync::watch;

use crate::state::HubState;

const VERSION: &str = env!("CARGO_PKG_VERSION");

// issue 1345 M3b: the Interkom phone PWA, embedded so the hub binary stays self-contained on
// strih-lx (same include_str!/include_bytes! model as bkshading). The relative paths resolve from
// `intercom/hub/src/` → `intercom/web/`. `janus.js` is vendored (MIT, tag v1.1.2 — see
// intercom/web/VENDORED.md); the icons are generated by intercom/web/gen-icons.py (stdlib, no dep).
const INDEX_HTML: &str = include_str!("../../web/index.html");
const APP_JS: &str = include_str!("../../web/app.js");
const STYLE_CSS: &str = include_str!("../../web/style.css");
const JANUS_JS: &str = include_str!("../../web/janus.js");
const MANIFEST_JSON: &str = include_str!("../../web/manifest.webmanifest");
const SW_JS: &str = include_str!("../../web/sw.js");
const ICON_192_PNG: &[u8] = include_bytes!("../../web/icon-192.png");
const ICON_512_PNG: &[u8] = include_bytes!("../../web/icon-512.png");
const FAVICON_SVG: &str = include_str!("../../web/favicon.svg");

// The Content-Type each PWA asset route serves, exposed so the route tests can pin the exact type
// without standing up an HTTP server (mirrors bkshading's `*_CONTENT_TYPE`).
pub const APP_JS_CONTENT_TYPE: &str = "text/javascript; charset=utf-8";
pub const STYLE_CSS_CONTENT_TYPE: &str = "text/css; charset=utf-8";
pub const JS_CONTENT_TYPE: &str = "text/javascript; charset=utf-8";
pub const MANIFEST_CONTENT_TYPE: &str = "application/manifest+json";
pub const SW_JS_CONTENT_TYPE: &str = "text/javascript; charset=utf-8";
pub const PNG_CONTENT_TYPE: &str = "image/png";
pub const SVG_CONTENT_TYPE: &str = "image/svg+xml";

/// The compiled hub version (the version-on-dashboard surface); exposed for the route tests.
pub fn pkg_version() -> &'static str {
    VERSION
}

/// The served PWA index with the version placeholder substituted (read straight from the DOM).
pub fn rendered_index() -> String {
    INDEX_HTML.replace("{{VERSION}}", VERSION)
}
/// The embedded phone app JS (issue 1345 M3b).
pub fn app_js_asset() -> &'static str {
    APP_JS
}
/// The embedded stylesheet.
pub fn style_css_asset() -> &'static str {
    STYLE_CSS
}
/// The vendored janus.js WebRTC library (MIT, tag v1.1.2).
pub fn janus_js_asset() -> &'static str {
    JANUS_JS
}
/// The embedded PWA manifest JSON.
pub fn manifest_asset() -> &'static str {
    MANIFEST_JSON
}
/// The embedded service worker JS (pure passthrough, no cache).
pub fn sw_js_asset() -> &'static str {
    SW_JS
}
/// The embedded 192px PWA icon PNG bytes.
pub fn icon_192_asset() -> &'static [u8] {
    ICON_192_PNG
}
/// The embedded 512px PWA icon PNG bytes.
pub fn icon_512_asset() -> &'static [u8] {
    ICON_512_PNG
}
/// The embedded SVG favicon.
pub fn favicon_svg_asset() -> &'static str {
    FAVICON_SVG
}

#[derive(Clone)]
pub struct AppState {
    /// The latest hub state, published by the block-status pump. Keeping a receiver here means the
    /// pump's `send` never fails for "no receivers".
    pub live: watch::Receiver<Arc<HubState>>,
}

pub fn router(state: AppState) -> Router {
    Router::new()
        .route("/", get(index))
        .route("/app.js", get(app_js))
        .route("/style.css", get(style_css))
        .route("/janus.js", get(janus_js))
        .route("/manifest.webmanifest", get(manifest))
        .route("/sw.js", get(service_worker))
        .route("/icon-192.png", get(icon_192))
        .route("/icon-512.png", get(icon_512))
        .route("/favicon.svg", get(favicon_svg))
        .route("/api/version", get(version))
        .route("/api/state", get(api_state))
        .route("/ws", get(ws_upgrade))
        .with_state(state)
}

/// The Interkom phone PWA index (issue 1345 M3b — replaces the M1 plain-text liveness page).
async fn index() -> Html<String> {
    Html(rendered_index())
}

async fn app_js() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, APP_JS_CONTENT_TYPE)], APP_JS)
}

async fn style_css() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, STYLE_CSS_CONTENT_TYPE)], STYLE_CSS)
}

async fn janus_js() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, JS_CONTENT_TYPE)], JANUS_JS)
}

async fn manifest() -> impl IntoResponse {
    (
        [(header::CONTENT_TYPE, MANIFEST_CONTENT_TYPE)],
        MANIFEST_JSON,
    )
}

async fn service_worker() -> impl IntoResponse {
    (
        [
            (header::CONTENT_TYPE, SW_JS_CONTENT_TYPE),
            // Allow the SW to control the whole origin even though it is served from /sw.js.
            (HeaderName::from_static("service-worker-allowed"), "/"),
        ],
        SW_JS,
    )
}

async fn icon_192() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, PNG_CONTENT_TYPE)], ICON_192_PNG)
}

async fn icon_512() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, PNG_CONTENT_TYPE)], ICON_512_PNG)
}

async fn favicon_svg() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, SVG_CONTENT_TYPE)], FAVICON_SVG)
}

async fn version() -> Json<serde_json::Value> {
    Json(serde_json::json!({ "version": VERSION }))
}

async fn api_state(State(state): State<AppState>) -> Json<Arc<HubState>> {
    Json(state.live.borrow().clone())
}

async fn ws_upgrade(State(state): State<AppState>, ws: WebSocketUpgrade) -> Response {
    ws.on_upgrade(move |socket| ws_push(socket, state.live.clone()))
}

/// Push the latest [`HubState`] to one client: the current state immediately, then a fresh state on
/// every pump update. Push-only (a browser panel sends nothing); the loop ends when the client goes
/// away or the pump is dropped (shutdown).
async fn ws_push(mut socket: WebSocket, mut rx: watch::Receiver<Arc<HubState>>) {
    loop {
        let snapshot = rx.borrow_and_update().clone();
        match ws_encode(&snapshot) {
            Ok(text) => {
                if socket.send(Message::Text(text)).await.is_err() {
                    break;
                }
            }
            Err(e) => {
                tracing::warn!(error = %e, "ws: serialize hub state failed");
                break;
            }
        }
        if rx.changed().await.is_err() {
            break;
        }
    }
}

/// Serialize a hub state for the WS wire (the exact text a `/ws` frame carries).
pub fn ws_encode(state: &HubState) -> Result<String, serde_json::Error> {
    serde_json::to_string(state)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::matrix::Matrix;
    use crate::state::{HubState, RuntimeStats};

    fn hub_state() -> HubState {
        let m = Matrix::from_toml(
            r#"
[hub]
bind = "0.0.0.0:8790"
vban_bind = "0.0.0.0:6980"
sample_rate = 48000
block_frames = 256

[[participant]]
name = "cam1"
role = "cambox"
adapter = "vban"
host = "cam1.lan"
in_stream = "cam1"
out_stream = "cam1"
in_channels = 2
out_channels = 2
"#,
        )
        .unwrap();
        HubState::snapshot(&m, "1.7.0-test", &[RuntimeStats::default()])
    }

    #[test]
    fn ws_encode_is_the_state_json() {
        let hs = hub_state();
        let text = ws_encode(&hs).unwrap();
        let v: serde_json::Value = serde_json::from_str(&text).unwrap();
        assert_eq!(v["version"], "1.7.0-test");
        assert_eq!(v["participants"][0]["name"], "cam1");
    }

    #[test]
    fn version_constant_is_populated() {
        assert!(!VERSION.is_empty());
    }

    #[test]
    fn index_is_the_pwa_not_the_m1_text_page() {
        // M3b: `/` now serves the installable PWA (the M1 plain-text page is gone), with the
        // version placeholder substituted for the DOM.
        let html = rendered_index();
        assert!(
            !html.contains("{{VERSION}}"),
            "version placeholder substituted"
        );
        assert!(html.contains("<!DOCTYPE html>"), "index is the PWA HTML");
        assert!(
            html.contains("data-role=\"connect\""),
            "the connect gesture button"
        );
        assert!(
            html.contains("/manifest.webmanifest"),
            "the PWA manifest is linked"
        );
    }
}
