//! `intercom-hub` — the strih-lx intercom mix-minus hub daemon (issue 1345 M1).
//!
//! Loads the declarative matrix, binds ONE VBAN receive socket, runs the N-1 mixer on a fixed
//! block cadence, sends each cambox's mix back over VBAN, and serves `/api/state` + `/ws`. M1 is
//! the VBAN leg only (the MiniFuse/PipeWire, Janus phones and Interkom video are M2/M3). Fails loud
//! on a malformed TOML or a socket bind failure — it never starts a half-configured intercom.
//!
//! NOTE: launching this against the live rig SENDS VBAN to the real camboxes. That is the M1b/M4
//! supervisor step (via the cam1 env override first) — never run it from a dev lane.

use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use anyhow::{Context, Result};
use clap::Parser;

use intercom_hub::engine::{Engine, InputBlock};
use intercom_hub::http::{router, AppState};
use intercom_hub::matrix::Matrix;
use intercom_hub::state::{HubState, RuntimeStats};
use intercom_hub::vban_io::{resolve_vban_addr, route_packet, JitterBuffer, OutBlock, VbanSender};

const VERSION: &str = env!("CARGO_PKG_VERSION");
const DEFAULT_CONFIG: &str = "/etc/intercom-hub/intercom.toml";

/// Jitter buffer depth = 8 blocks per participant (older samples drop as an overrun).
const JITTER_CAP_BLOCKS: usize = 8;
/// How often the output hosts are re-resolved off the hot path (DHCP lease moves).
const OUTPUT_RESOLVE_REFRESH_S: u64 = 60;

#[derive(Parser, Debug)]
#[command(
    name = "intercom-hub",
    version,
    about = "strih-lx intercom mix-minus hub (issue 1345)"
)]
struct Args {
    /// Path to the intercom routing TOML (generated by scripts/vbmatrix_to_intercom_toml.py).
    #[arg(long, default_value = DEFAULT_CONFIG)]
    config: PathBuf,

    /// Override the HTTP bind address (host:port) from the config's `[hub].bind`.
    #[arg(long)]
    bind: Option<String>,
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()),
        )
        .init();

    let args = Args::parse();

    // Fail loud on a missing/malformed matrix — never start a half-configured intercom.
    let text = std::fs::read_to_string(&args.config)
        .with_context(|| format!("read intercom config {}", args.config.display()))?;
    let matrix = Matrix::from_toml(&text)
        .with_context(|| format!("parse intercom config {}", args.config.display()))?;

    let http_bind = args.bind.clone().unwrap_or_else(|| matrix.hub.bind.clone());
    let http_addr: SocketAddr = http_bind
        .parse()
        .with_context(|| format!("invalid http bind '{http_bind}'"))?;
    let sample_rate = matrix.hub.sample_rate;
    let block_frames = matrix.hub.block_frames;
    let n = matrix.participants.len();

    // The VBAN receive socket — fail loud on a bind failure (port already in use, bad address).
    let vban_socket = tokio::net::UdpSocket::bind(&matrix.hub.vban_bind)
        .await
        .with_context(|| format!("bind VBAN socket {}", matrix.hub.vban_bind))?;

    let input_streams = matrix.vban_input_streams();
    let outputs = matrix.vban_outputs();
    let n_outputs = outputs.len();
    // Output destinations are resolved ONCE here and refreshed by a background task every
    // OUTPUT_RESOLVE_REFRESH_S (a cambox on a new DHCP lease is picked up within a minute) — the
    // block loop below only ever sends to a cached SocketAddr. A host STRING on that hot path was a
    // synchronous getaddrinfo per 5.33 ms block (M1b live finding, 19.9.2026: ~95 pkt/s instead of
    // 187.5 + a jitter-buffer overrun storm). A failed refresh keeps the last-known-good address.
    let out_addrs: Arc<Mutex<Vec<Option<SocketAddr>>>> = Arc::new(Mutex::new(
        outputs
            .iter()
            .map(|(_, stream, host)| {
                let a = resolve_vban_addr(host, intercom_vban::VBAN_PORT);
                match a {
                    Some(addr) => tracing::info!(%stream, %host, %addr, "VBAN output resolved"),
                    None => tracing::warn!(%stream, %host, "VBAN output UNRESOLVED at start — will retry every {OUTPUT_RESOLVE_REFRESH_S}s"),
                }
                a
            })
            .collect(),
    ));
    {
        let out_addrs = out_addrs.clone();
        let hosts: Vec<String> = outputs.iter().map(|(_, _, h)| h.clone()).collect();
        tokio::spawn(async move {
            let mut ticker =
                tokio::time::interval(std::time::Duration::from_secs(OUTPUT_RESOLVE_REFRESH_S));
            ticker.tick().await; // the first tick fires immediately; startup already resolved
            loop {
                ticker.tick().await;
                let hosts = hosts.clone();
                let fresh = tokio::task::spawn_blocking(move || {
                    hosts
                        .iter()
                        .map(|h| resolve_vban_addr(h, intercom_vban::VBAN_PORT))
                        .collect::<Vec<_>>()
                })
                .await;
                if let (Ok(fresh), Ok(mut cur)) = (fresh, out_addrs.lock()) {
                    for (slot, a) in cur.iter_mut().zip(fresh) {
                        if a.is_some() && *slot != a {
                            tracing::info!(old = ?*slot, new = ?a, "VBAN output address changed");
                            *slot = a;
                        }
                    }
                }
            }
        });
    }
    let engine = Arc::new(Engine::new(matrix.clone()));
    let jitter: Arc<Mutex<Vec<JitterBuffer>>> = Arc::new(Mutex::new(
        (0..n)
            .map(|_| JitterBuffer::new(block_frames * JITTER_CAP_BLOCKS))
            .collect(),
    ));

    // Seed the live channel so a client connecting before the first tick sees current state.
    let initial = Arc::new(HubState::snapshot(
        &matrix,
        VERSION,
        &vec![RuntimeStats::default(); n],
    ));
    let (live_tx, live_rx) = tokio::sync::watch::channel(initial);

    // --- receive task: demux packets into per-participant jitter buffers ---------------------
    {
        let jitter = jitter.clone();
        tokio::spawn(async move {
            let mut buf = vec![0u8; 65536];
            loop {
                match vban_socket.recv_from(&mut buf).await {
                    Ok((len, _from)) => {
                        if let Some((id, audio)) = route_packet(&input_streams, &buf[..len]) {
                            if let Ok(mut jb) = jitter.lock() {
                                if let Some(b) = jb.get_mut(id) {
                                    b.push(&audio);
                                }
                            }
                        }
                    }
                    Err(e) => {
                        tracing::warn!(error = %e, "VBAN recv error");
                    }
                }
            }
        });
    }

    // --- block/mix task: pop a block from every buffer, mix N-1, send each cambox's stream ----
    {
        let jitter = jitter.clone();
        let engine = engine.clone();
        let matrix = matrix.clone();
        let out_addrs = out_addrs.clone();
        let sender = VbanSender::bind_ephemeral().context("bind VBAN send socket")?;
        // Status push cadence: ~1 s worth of blocks.
        let status_every = ((sample_rate as usize) / block_frames.max(1)).max(1);
        tokio::spawn(async move {
            let period = std::time::Duration::from_micros(
                (block_frames as u64) * 1_000_000 / (sample_rate.max(1) as u64),
            );
            let mut ticker = tokio::time::interval(period);
            ticker.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
            let mut tx_packets = vec![0u64; n];
            let mut frame_counter = vec![0u32; n];
            let mut cycle: u64 = 0;
            loop {
                ticker.tick().await;
                cycle = cycle.wrapping_add(1);

                // Pop one block per participant + gather rx stats under the lock.
                let mut input = InputBlock::silent(n);
                let mut rx_stats = vec![RuntimeStats::default(); n];
                if let Ok(mut jb) = jitter.lock() {
                    for (id, b) in jb.iter_mut().enumerate() {
                        input.set(id, b.pop_block(block_frames));
                        rx_stats[id].rx_packets = b.rx_packets;
                        rx_stats[id].underruns = b.underruns;
                        rx_stats[id].overruns = b.overruns;
                        rx_stats[id].last_rx_age_ms = b.last_rx_age_ms();
                        rx_stats[id].level_dbfs = b.last_level_dbfs();
                    }
                }

                let output = engine.mix_block(&input, block_frames);

                // Send each cambox its mixed stereo stream — to the CACHED resolved address only.
                let addrs: Vec<Option<SocketAddr>> =
                    out_addrs.lock().map(|a| (*a).clone()).unwrap_or_default();
                for (slot, (id, stream, host)) in outputs.iter().enumerate() {
                    let Some(addr) = addrs.get(slot).copied().flatten() else {
                        if cycle.is_multiple_of(status_every as u64) {
                            tracing::warn!(%stream, %host, "VBAN output still unresolved — not sending");
                        }
                        continue;
                    };
                    let chans = matrix.participants[*id].out_channels.max(1) as u8;
                    let interleaved = output.interleaved(*id, block_frames);
                    frame_counter[*id] = frame_counter[*id].wrapping_add(1);
                    let block = OutBlock {
                        stream_name: stream,
                        sample_rate,
                        channels: chans,
                        frame_counter: frame_counter[*id],
                        interleaved: &interleaved,
                        frames: block_frames,
                    };
                    match sender.send_block(addr, &block) {
                        Ok(()) => tx_packets[*id] = tx_packets[*id].wrapping_add(1),
                        Err(e) => {
                            tracing::debug!(target: "vban_send", %stream, %host, %addr, error=%e, "VBAN send failed")
                        }
                    }
                }

                if cycle.is_multiple_of(status_every as u64) {
                    for (id, s) in rx_stats.iter_mut().enumerate() {
                        s.tx_packets = tx_packets[id];
                    }
                    let snapshot = HubState::snapshot(&matrix, VERSION, &rx_stats);
                    tracing::info!("{}", snapshot.status_line());
                    let _ = live_tx.send(Arc::new(snapshot));
                }
            }
        });
    }

    tracing::info!(
        version = VERSION,
        %http_addr,
        participants = n,
        vban_bind = %matrix.hub.vban_bind,
        outputs = n_outputs,
        "intercom-hub starting"
    );

    let state = AppState { live: live_rx };
    let listener = tokio::net::TcpListener::bind(http_addr)
        .await
        .with_context(|| format!("bind HTTP {http_addr}"))?;
    axum::serve(listener, router(state))
        .with_graceful_shutdown(shutdown_signal())
        .await?;
    Ok(())
}

async fn shutdown_signal() {
    let _ = tokio::signal::ctrl_c().await;
    tracing::info!("intercom-hub shutting down");
}
